apiVersion: v1
kind: PersistentVolume
metadata:
  name: fl-checkpoints-pv
  namespace: lge-ebme
spec:
  storageClassName: local-path
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/checkpoints"
