apiVersion: v1
kind: Service
metadata:
  namespace: lge-ebme
  name: fl-superlink-svc
spec:
  type: NodePort
  selector:
    app: fl-superlink
  ports:
    - protocol: TCP
      port: 9091
      nodePort: 30091
      name: superlink1
    - protocol: TCP
      port: 9092
      nodePort: 30092
      name: superlink2
    - protocol: TCP
      port: 9093
      nodePort: 30093
      name: superlink3
