apiVersion: v1
kind: PersistentVolume
metadata:
  name: fl-checkpoints-pv
  namespace: lge-ebme
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/checkpoints"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - kube-cluster-worker1
                - kube-cluster-worker3
                - kube-cluster-worker4
