apiVersion: batch/v1
kind: CronJob
metadata:
  name: fl-client-2-cronjob
  namespace: lge-ebme
spec:
  schedule: "*/3 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: fl-client-2
        spec:
          containers:
            - name: fl-client-2
              image: lgecloudroboticstask/fl:latest
              imagePullPolicy: Always
              command: ["/bin/bash", "-c", "python client.py"]
              env:
                - name: SERVER_IP
                  value: "10.177.196.41"
                - name: SERVER_PORT
                  value: "30180"
              resources:
                requests:
                  cpu: 1000m
                  memory: 512Mi
                limits:
                  cpu: 8000m
                  memory: 16Gi
              volumeMounts:
                - mountPath: /mnt/checkpoints
                  name: checkpoints
          volumes:
            - name: checkpoints
              persistentVolumeClaim:
                claimName: fl-checkpoints-pvc
          restartPolicy: OnFailure
          imagePullSecrets:
            - name: regcred
          nodeSelector:
            kubernetes.io/hostname: kube-cluster-worker4
