apiVersion: v1
kind: Service
metadata:
  namespace: lge-ebme
  name: fl-server-svc
spec:
  type: NodePort
  selector:
    app: fl-server
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30180
